name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2  # Change this to the Ruby version you are using

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build --future
